Update sumit.yaml

diff --git a/.github/workflows/sumit.yaml b/.github/workflows/sumit.yaml
--- a/.github/workflows/sumit.yaml
+++ b/.github/workflows/sumit.yaml
@@ -153,5 +153,5 @@ jobs:
       - name: Deploy Application
         run: |
           echo "Starting deployment..."
-          ssh -i ~/.ssh/id_rsa root@128.199.28.236 "chmod +x /root/deploy.sh && /root/deploy.sh" || { echo 'Deployment failed'; exit 1; }
+          ssh -i ~/.ssh/id_rsa root@128.199.28.236 "chmod +x /root/aws.sh && /root/aws.sh" || { echo 'Deployment failed'; exit 1; }
           echo "Deployment completed successfully."
