Update sumit.yaml

diff --git a/.github/workflows/sumit.yaml b/.github/workflows/sumit.yaml
--- a/.github/workflows/sumit.yaml
+++ b/.github/workflows/sumit.yaml
@@ -105,7 +105,7 @@ jobs:
         run: |
           ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@128.199.28.236 "echo 'SSH connection successful'" || { echo "SSH connection to remote server failed"; exit 1; }
 
-      - name: Deploy
+      - name: Deploy Application
         run: |
-          ssh -i ~/.ssh/id_rsa root@128.199.28.236 "bash -s" < ./deploy.sh || { echo "Deployment failed"; exit 1; }
+          ssh -i ~/.ssh/id_rsa root@128.199.28.236 "chmod +x /root/deploy.sh && /root/deploy.sh" || { echo 'Deployment failed'; exit 1; }
 
